apiVersion: apps/v1
kind: Deployment
metadata:
  name: poiskkino-bot
  namespace: kinopoisk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poiskkino-bot
  template:
    metadata:
      labels:
        app: poiskkino-bot
    spec:
      containers:
        - name: poiskkino-bot
          image: mdwit/kp-bot:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: poiskkino-bot
      imagePullSecrets:
        - name: regcred
